# `StandardScaler` does not change the result on `MinMaxScaler`

In [1]:
from sklearn import preprocessing
import numpy as np

In [2]:
X_train = np.array([
    [ 1., -1.,  5.],
    [ 2.,  0.,  0.],
    [ 0.,  1., -1.],
])

In [3]:
scaler = preprocessing.StandardScaler().fit(X_train)
X_scaled = scaler.transform(X_train)
X_scaled

array([[ 0.        , -1.22474487,  1.3970014 ],
       [ 1.22474487,  0.        , -0.50800051],
       [-1.22474487,  1.22474487, -0.88900089]])

In [4]:
minmax = preprocessing.MinMaxScaler()
minmax.fit_transform(X_scaled)


array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.16666667],
       [0.        , 1.        , 0.        ]])

In [5]:
minmax.fit_transform(X_train)

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.16666667],
       [0.        , 1.        , 0.        ]])